version: "3.9"
services:
  php-fpm:
    build:
      context: .
      dockerfile: PHP.Dockerfile
    depends_on:
      - mysql
    links:
      - mysql
    volumes:
      - ./:/var/www/html/
      - ./config/php.ini:/usr/local/etc/php/conf.d/php.ini
    ports:
      - "9000"
    environment:
     - DB_HOST=mysql
     - DB_USER=mysql
     - DB_PASS=mysql
     - DB_NAME=natverk_development
     - DB_PORT=3306
  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./:/var/www/html/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
  mysql:
    image: mariadb:10.7
    command: '--default-authentication-plugin=mysql_native_password --general-log'
    volumes:
      - ./tmp/db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=natverk_development
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
    ports:
      - "3306:3306"
