version: "3.9"
services:
  php-fpm:
    image: php:fpm
    volumes:
      - ./:/var/www/html/
    ports:
      - "9000"
  nginx:
    image: nginx:alpine
    depends_on:
      - php-fpm
    links:
      - php-fpm
    volumes:
      - ./:/var/www/html/
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
